src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageFilename = null;

    #[ORM\Column]
    private ?int $price = null;

    /**
     * @var Collection<int, ProductVariant>
     */
    #[ORM\OneToMany(targetEntity: ProductVariant::class, mappedBy: 'Relation')]
    private Collection $variants;

    #[ORM\Column]
    private ?bool $isFeatured = null;

    public function __construct()
    {
        $this->variants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, ProductVariant>
     */
    public function getVariants(): Collection
    {
        return $this->variants;
    }

    public function addVariant(ProductVariant $variant): static
    {
        if (!$this->variants->contains($variant)) {
            $this->variants->add($variant);
            $variant->setRelation($this);
        }

        return $this;
    }

    public function removeVariant(ProductVariant $variant): static
    {
        if ($this->variants->removeElement($variant)) {
            // set the owning side to null (unless already changed)
            if ($variant->getRelation() === $this) {
                $variant->setRelation(null);
            }
        }

        return $this;
    }

    public function isFeatured(): ?bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(bool $isFeatured): static
    {
        $this->isFeatured = $isFeatured;

        return $this;
    }

    public function getPriceInEuros(): float
    {
        return $this->price / 100;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->getPriceInEuros(), 2, ',', ' ') . ' €';
    }
}

templates/admin_dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Back-office administrateur{% endblock %}

{% block body %}
{% set sizes = {'XS':'XS', 'S':'S', 'M':'M', 'L':'L', 'XL':'XL'} %}

<div class="container mt-4">
    <div class="card bg-add mb-5 p-3">
        <h2 class="mb-4">Ajouter un nouveau produit</h2>
            {{ form_start(newForm) }}
                <div class="row align-items-center mb-3">
                    <div class="row p-3">
                        <div class="col">
                            {{ form_row(newForm.imageFile) }}
                        </div>
                        
                        <div class="col">
                            {{ form_row(newForm.name) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.price) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.isFeatured) }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {{ form_row(newForm.stockXS) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.stockS) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.stockM) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.stockL) }}
                        </div>

                        <div class="col">
                            {{ form_row(newForm.stockXL) }}
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end mb-3">
                    <button type="submit">Ajouter</button>
                </div>
            {{ form_end(newForm) }}
    </div>

    <div class="card mb-5 p-3">
    <h2 class="mb-4">Produits existants</h2>
    {% for product in products %}
        <div class="card mb-4 p-3">
            <div class="d-flex align-items-stretch">
                {% if product.imageFilename %}
                    <div class="me-3 d-flex flex-column justify-content-between">
                        <img src="{{ asset('uploads/images/' ~ product.imageFilename) }}" alt="{{ product.name }}" width="150">
                        <div class="mt-3">
                    </div>
                {% endif %}

                <div class="d-flex flex-column justify-content-center flex-grow-1">
                    <div class="d-flex flex-wrap align-items-center">
                        <h5 class="me-4 mb-0">{{ product.name }}</h5>
                        <div class="me-4"><strong>Prix :</strong> {{ product.formattedPrice }}</div>

                        {% for sizeLabel, sizeCode in sizes %}
                            <div class="me-3">
                                <strong>{{ sizeCode }} :</strong>
                                {% set stock = 0 %}
                                {% for variant in product.variants %}
                                    {% if variant.size == sizeCode %}
                                        {% set stock = variant.stock %}
                                    {% endif %}
                                {% endfor %}
                                {{ stock }}
                            </div>
                        {% endfor %}

                        <div class="ms-auto">
                            <strong>Mis en avant :</strong>
                            {{ product.isFeatured ? 'Oui' : 'Non' }}
                        </div>
                    </div>
                </div>

                <div class="d-flex">
                    <a href="{{ path('product_edit_page', {'id': product.id}) }}" class="btn btn-primary me-2">Modifier</a>

                    {{ form_start(deleteForms[product.id]) }}
                        {{ form_widget(deleteForms[product.id]) }}
                        <button type="submit" class="btn btn-primary me-2">Supprimer</button>
                    {{ form_end(deleteForms[product.id]) }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Stubborn, Don't compromise on your look{% endblock %}</title>
        <link rel="icon" href="{{ asset('favicon.png') }}" type="image/png">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {# Header #}
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand d-flex flex-column align-items-center" href="{{ path('app_home') }}">
                    <img src="{{ asset('Logo.png') }}" class="me-2 mb-1" alt="Logo Stubborn" width="150" height="120">
                    Don't compromise on your look
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% set current = app.request.attributes.get('_route') %}
                    <ul class="navbar-nav ms-auto align-items-center mb-2 mb-lg-0">
                    
                    {# ROLE_ADMIN #}
                    {% if is_granted('ROLE_ADMIN') %}
                       <li class="nav-item">
                            <a class="nav-link {{ current == 'admin_dashboard' ? 'active' }}" href="{{ path('admin_dashboard')}}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_home' ? 'active' }}" href="{{ path('product_index')}}">Boutique</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current starts with 'admin_users' ? 'active' }}" href="{{ path('admin_users') }}">Gérer les administrateurs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_logout' ? 'active' }}" href="{{ path('app_logout') }}">Se déconnecter</a>
                        </li>
                    
                    {# ROLE_USER #}
                    {% elseif is_granted('ROLE_USER') %}
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_home' ? 'active' }}" href="{{ path('app_home') }}">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'product_index' ? 'active' }}" href="{{ path('product_index')}}">Boutique</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current starts with 'cart_' ? 'active' }}" href="{{ path('cart_show') }}">Panier</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_logout' ? 'active' }}" href="{{ path('app_logout') }}">Se déconnecter</a>
                        </li>
                    
                    {# Non connecté #}
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_home' ? 'active' }}" href="{{ path('app_home') }}">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_register' ? 'active' }}" href="{{ path('app_register') }}">S'inscrire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ current == 'app_login' ? 'active' }}" href="{{ path('app_login') }}">Se connecter</a>
                        </li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {# Message flash #}
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        <main class="container">
        {% block body %}{% endblock %}
        </main>

        <footer class="bg-dark text-center p-3 mt-5">
            <div class="text-white">
                <h2>Stubborn</h2>
                <address>Piccadilly Circus<br/>
                    LONDON W1J 0DA<br/>
                    ROYAUME UNI<br/>
                    <a href="mailto:stubborn@blabla.com">stubborn@blabla.com</a>
                </address>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </body>
</html>